[package]
name = "notty"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]
license = "AGPL-3.0+"

[dependencies]
image = "0.5.0"
mime = "0.1.0"
unicode-width = "0.1.3"
base64 = "0.1.1"

[dependencies.notty-encoding]
git = "https://github.com/withoutboats/notty-encoding"
